chore: bump clap to v4.2.4 for v1.69 clippy lints
Details can be seen in clap-rs/clap#4733.
Using Subcommand with old clap versions causes clippy 1.69 to complain.
In this case it was:
```
error: this looks like you are trying to swap `arg` and `cmd`
   --> src/bin/cog/main.rs:292:23
```